version: 2
jobs:
  build-job:
    docker:
      - { image: 'circleci/golang:1.8' }
    working_directory: /go/src/github.com/demoulin/sock5-server
    steps:
      '-run': { command: "docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD\n  if [ $CIRCLE_TAG -ne \"undefined\" ];\n  then\n    docker tag demoulin/go-socks5-proxy demoulin/go-socks5-proxy:$CIRCLE_TAG\n    docker push demoulin/go-socks5-proxy:$CIRCLE_TAG\n  else\n    docker tag demoulin/go-socks5-proxy demoulin/go-socks5-proxy:dev\n    docker push demoulin/go-socks5-proxy:dev\n  fi\n" }
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - { deploy-job: { requires: [build-job] } }
